from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT_ROOT = ROOT / ".agents" / "skills" / "skillguard" / "scripts"
if str(SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPT_ROOT))

from skillguard_v2.consumer_distribution import (  # noqa: E402
    audit_consumer_distribution,
    build_consumer_distribution,
)
from skillguard_v2.wire_identity import (  # noqa: E402
    CONSUMER_RELEASE_WIRE_POLICY_ID,
    consumer_release_canonical_json_bytes,
    consumer_release_wire_hash,
    is_consumer_release_wire_hash,
)


CLAIM_BOUNDARY = (
    "This manifest identifies target-owned consumer files only. It carries no "
    "author contract, receipt, router, session, cache, or execution authority."
)

# This vector is generated by FlowGuard's distribution_sync implementation for
# the same two-file source fixture.  Keeping the expected bytes and identities
# literal makes this an inter-project contract test rather than a second call
# to the SkillGuard producer under test.
FLOWGUARD_REFERENCE_MANIFEST = (
    b'{"author_control_excluded":true,"claim_boundary":"This manifest identifies '
    b'target-owned consumer files only. It carries no author contract, receipt, '
    b'router, session, cache, or execution authority.","files":[{"content_hash":'
    b'"sha256:a0ac7db66ef769cfac4bfb742c3aa8d53c6c86d0b132c2a09936391f8935f6af",'
    b'"path":"SKILL.md"},{"content_hash":"sha256:efe53b3820404f83fa0a8150d0443c27fbe605e43134309358a663f9989aee6a",'
    b'"path":"scripts/run.py"}],"manifest_hash":"sha256:85eccf0a8b32dd3882b26d343ac83609ad2b9ee237496edf867da19b773652be",'
    b'"projection_id":"projection:consumer-distribution","release_id":"sha256:9abb8a09ef01437d3cc3b8b926cc4f4bcaa8f21ea9866125dc78df9487dafa4e",'
    b'"schema_version":"consumer.skill_distribution.current","skill_id":"demo"}\n'
)


def _contract() -> dict[str, object]:
    return {
        "skill_id": "demo",
        "maintenance_unit_id": "unit:demo",
        "contract_hash": "sha256:" + "1" * 64,
        "consumer_projection": {"release_manifest_path": "consumer-release.json"},
    }


def _fixture_source(root: Path) -> Path:
    source = root / "source"
    (source / "scripts").mkdir(parents=True)
    (source / "SKILL.md").write_text("# Demo\n", encoding="utf-8")
    (source / "scripts" / "run.py").write_text("print('ready')\n", encoding="utf-8")
    return source


class ConsumerReleaseWireProtocolTests(unittest.TestCase):
    def test_wire_policy_is_compact_lowercase_and_flowguard_compatible(self) -> None:
        payload = {"b": "x", "a": 1}
        self.assertEqual(
            CONSUMER_RELEASE_WIRE_POLICY_ID,
            "consumer.skill_distribution.wire.current",
        )
        self.assertEqual(
            consumer_release_canonical_json_bytes(payload),
            b'{"a":1,"b":"x"}',
        )
        self.assertEqual(
            consumer_release_wire_hash(payload),
            "sha256:ecf9e98ec0641e23113ff3ce8bdc78d0ddd249886517fd4a7f68cc83d4e65667",
        )
        self.assertTrue(is_consumer_release_wire_hash(consumer_release_wire_hash(payload)))
        self.assertFalse(is_consumer_release_wire_hash("SHA256:" + "A" * 64))
        self.assertFalse(is_consumer_release_wire_hash("A" * 64))

    def test_skillguard_producer_matches_flowguard_reference_manifest_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = _fixture_source(root)
            destination = root / "consumer"

            result = build_consumer_distribution(source, destination, _contract())

            self.assertEqual("passed", result["status"])
            manifest_path = destination / "consumer-release.json"
            self.assertEqual(FLOWGUARD_REFERENCE_MANIFEST, manifest_path.read_bytes())
            manifest = json.loads(FLOWGUARD_REFERENCE_MANIFEST)
            self.assertEqual(
                "sha256:9abb8a09ef01437d3cc3b8b926cc4f4bcaa8f21ea9866125dc78df9487dafa4e",
                manifest["release_id"],
            )
            self.assertEqual(
                "sha256:85eccf0a8b32dd3882b26d343ac83609ad2b9ee237496edf867da19b773652be",
                manifest["manifest_hash"],
            )
            self.assertEqual("passed", audit_consumer_distribution(destination)["status"])

    def test_skillguard_verifier_accepts_external_flowguard_manifest_and_rejects_pretty_reseal(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = _fixture_source(root)
            consumer = root / "consumer"
            consumer.mkdir()
            (consumer / "SKILL.md").write_text(
                (source / "SKILL.md").read_text(encoding="utf-8"), encoding="utf-8"
            )
            (consumer / "scripts").mkdir()
            (consumer / "scripts" / "run.py").write_text(
                (source / "scripts" / "run.py").read_text(encoding="utf-8"),
                encoding="utf-8",
            )
            manifest_path = consumer / "consumer-release.json"
            manifest_path.write_bytes(FLOWGUARD_REFERENCE_MANIFEST)

            self.assertEqual("passed", audit_consumer_distribution(consumer)["status"])

            manifest = json.loads(FLOWGUARD_REFERENCE_MANIFEST)
            manifest_path.write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            audited = audit_consumer_distribution(consumer)
            self.assertEqual("blocked", audited["status"])
            self.assertIn(
                "consumer_release_manifest_noncanonical",
                {row["code"] for row in audited["findings"]},
            )


if __name__ == "__main__":
    unittest.main()
