"""Build and verify independently usable target-skill consumer distributions."""

from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from .contract_compiler import canonical_hash


CONSUMER_RELEASE_SCHEMA = "consumer.skill_distribution.current"
DEFAULT_RELEASE_MANIFEST = "consumer-release.json"
TEXT_SUFFIXES = frozenset(
    {
        ".md",
        ".txt",
        ".json",
        ".jsonl",
        ".yaml",
        ".yml",
        ".toml",
        ".py",
        ".ps1",
        ".sh",
        ".js",
        ".ts",
        ".tsx",
        ".jsx",
        ".html",
        ".css",
        ".xml",
        ".ini",
        ".cfg",
    }
)
ALWAYS_EXCLUDED_NAMES = frozenset(
    {".git", ".hg", ".svn", "__pycache__", ".pytest_cache", ".mypy_cache"}
)
AUTHOR_CONTROL_PREFIXES = (".skillguard/",)
FORBIDDEN_RUNTIME_PATTERNS = (
    ("consumer_skillguard_path_reference", re.compile(r"(?i)(?:^|[\\/'\"`])\.skillguard(?:[\\/]|$)")),
    ("consumer_skillguard_command_reference", re.compile(r"(?i)\bskillguard(?:\.py)?\b")),
    ("consumer_skillguard_import_reference", re.compile(r"(?im)^\s*(?:from|import)\s+skillguard(?:\b|\.)")),
    ("consumer_portfolio_authority_reference", re.compile(r"(?i)\bportfolio[_ -](?:receipt|reuse|evidence|graduation)\b")),
)


@dataclass(frozen=True)
class ConsumerDistributionFinding:
    code: str
    path: str
    detail: str

    def to_dict(self) -> dict[str, str]:
        return {"code": self.code, "path": self.path, "detail": self.detail}


def _relative_files(root: Path) -> tuple[tuple[str, Path], ...]:
    rows: list[tuple[str, Path]] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if any(part in ALWAYS_EXCLUDED_NAMES for part in relative.parts):
            continue
        if path.is_symlink():
            rows.append((relative.as_posix(), path))
        elif path.is_file():
            rows.append((relative.as_posix(), path))
    return tuple(rows)


def _file_hash(path: Path) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(64 * 1024), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def _read_text(path: Path) -> str | None:
    if path.suffix.lower() not in TEXT_SUFFIXES and path.name != "SKILL.md":
        return None
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return None


def consumer_distribution_plan(
    skill_root: Path,
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Return the exact consumer file inventory and all pre-copy blockers."""

    root = skill_root.resolve()
    projection = contract.get("consumer_projection", {})
    if not isinstance(projection, Mapping):
        projection = {}
    release_manifest_path = str(
        projection.get("release_manifest_path", DEFAULT_RELEASE_MANIFEST)
    )
    impact_plan = contract.get("content_impact_plan", {})
    inventory_dispositions: dict[str, str] = {}
    member_root_path = "."
    if isinstance(impact_plan, Mapping):
        member_root_path = str(impact_plan.get("member_root_path", ".")).strip("/")
        inventory_dispositions = {
            str(row.get("path", "")).replace("\\", "/"): str(
                row.get("install_disposition", "")
            )
            for row in impact_plan.get("inventory", [])
            if isinstance(row, Mapping)
        }
    findings: list[ConsumerDistributionFinding] = []
    files: list[dict[str, str]] = []
    stranded_runtime_root = root / ".skillguard" / "runtime"
    if stranded_runtime_root.is_dir():
        for relative, path in _relative_files(stranded_runtime_root):
            findings.append(
                ConsumerDistributionFinding(
                    "target_runtime_stranded_in_author_control",
                    f".skillguard/runtime/{relative}",
                    "move target-domain runtime into a target-owned namespace before graduation",
                )
            )
    for relative, path in _relative_files(root):
        normalized = relative.replace("\\", "/")
        if normalized == release_manifest_path:
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_release_manifest_source_collision",
                    normalized,
                    "the release manifest is generated by the consumer builder",
                )
            )
            continue
        if any(normalized == prefix.rstrip("/") or normalized.startswith(prefix) for prefix in AUTHOR_CONTROL_PREFIXES):
            continue
        inventory_path = (
            normalized
            if member_root_path in {"", "."}
            else f"{member_root_path}/{normalized}"
        )
        if inventory_dispositions.get(inventory_path) == "source_only":
            continue
        if "skillguard" in normalized.lower():
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_author_control_name_present",
                    normalized,
                    "consumer paths must use target-owned names",
                )
            )
        if path.is_symlink():
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_symlink_forbidden",
                    normalized,
                    "consumer distributions contain regular files only",
                )
            )
            continue
        text = _read_text(path)
        if text is not None:
            for code, pattern in FORBIDDEN_RUNTIME_PATTERNS:
                if pattern.search(text):
                    findings.append(
                        ConsumerDistributionFinding(
                            code,
                            normalized,
                            "consumer files must not require or instruct use of author-side SkillGuard state",
                        )
                    )
        files.append({"path": normalized, "content_hash": _file_hash(path)})
    files.sort(key=lambda row: row["path"])
    identity = {
        "schema_version": CONSUMER_RELEASE_SCHEMA,
        "skill_id": str(contract.get("skill_id", "")),
        "projection_id": "projection:consumer-distribution",
        "files": files,
        "author_control_excluded": True,
    }
    release_id = canonical_hash(identity)
    return {
        **identity,
        "release_id": release_id,
        "release_manifest_path": release_manifest_path,
        "author_maintenance_binding": {
            "maintenance_unit_id": str(contract.get("maintenance_unit_id", "")),
            "source_contract_hash": str(contract.get("contract_hash", "")),
        },
        "status": "blocked" if findings else "passed",
        "findings": [finding.to_dict() for finding in findings],
    }


def build_consumer_distribution(
    skill_root: Path,
    destination_root: Path,
    contract: Mapping[str, Any],
) -> dict[str, Any]:
    """Create a new consumer tree only after a complete no-author-control preflight."""

    source = skill_root.resolve()
    destination = destination_root.absolute()
    plan = consumer_distribution_plan(source, contract)
    if plan["status"] != "passed":
        return plan
    if destination.exists() or destination.is_symlink():
        raise FileExistsError("consumer_distribution_destination_exists")
    destination.mkdir(parents=True, exist_ok=False)
    try:
        for row in plan["files"]:
            relative = Path(*str(row["path"]).split("/"))
            source_path = (source / relative).resolve(strict=True)
            if not source_path.is_relative_to(source) or not source_path.is_file():
                raise ValueError("consumer_distribution_source_member_unsafe")
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_path, target)
        manifest = {
            key: plan[key]
            for key in (
                "schema_version",
                "skill_id",
                "projection_id",
                "release_id",
                "files",
                "author_control_excluded",
            )
        }
        manifest["claim_boundary"] = (
            "This manifest identifies target-owned consumer files only. It carries no "
            "author contract, receipt, router, session, cache, or execution authority."
        )
        manifest["manifest_hash"] = canonical_hash(manifest)
        manifest_path = destination / str(plan["release_manifest_path"])
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = manifest_path.with_name(
            f".{manifest_path.name}.{os.getpid()}.tmp"
        )
        temporary.write_text(
            json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":")),
            encoding="utf-8",
        )
        os.replace(temporary, manifest_path)
    except Exception:
        shutil.rmtree(destination)
        raise
    return audit_consumer_distribution(destination)


def audit_consumer_distribution(root: Path) -> dict[str, Any]:
    """Verify one built or installed consumer tree without executing it."""

    tree = root.resolve()
    manifest_path = tree / DEFAULT_RELEASE_MANIFEST
    findings: list[ConsumerDistributionFinding] = []
    if not manifest_path.is_file():
        return {
            "schema_version": CONSUMER_RELEASE_SCHEMA,
            "status": "blocked",
            "findings": [
                ConsumerDistributionFinding(
                    "consumer_release_manifest_missing",
                    DEFAULT_RELEASE_MANIFEST,
                    "consumer distribution identity is absent",
                ).to_dict()
            ],
        }
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        manifest = {}
    if not isinstance(manifest, dict):
        manifest = {}
    unsigned = dict(manifest)
    stored_hash = unsigned.pop("manifest_hash", None)
    if (
        manifest.get("schema_version") != CONSUMER_RELEASE_SCHEMA
        or manifest.get("projection_id") != "projection:consumer-distribution"
        or manifest.get("author_control_excluded") is not True
        or stored_hash != canonical_hash(unsigned)
    ):
        findings.append(
            ConsumerDistributionFinding(
                "consumer_release_manifest_invalid",
                DEFAULT_RELEASE_MANIFEST,
                "manifest schema, projection, or immutable hash is invalid",
            )
        )
    expected = {
        str(row.get("path", "")): str(row.get("content_hash", ""))
        for row in manifest.get("files", [])
        if isinstance(row, Mapping)
    }
    actual: dict[str, str] = {}
    for relative, path in _relative_files(tree):
        normalized = relative.replace("\\", "/")
        if normalized == DEFAULT_RELEASE_MANIFEST:
            continue
        if normalized.startswith(".skillguard/") or normalized == ".skillguard":
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_author_control_path_present",
                    normalized,
                    "consumer trees must contain zero .skillguard paths",
                )
            )
            continue
        if "skillguard" in normalized.lower():
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_author_control_name_present",
                    normalized,
                    "consumer paths must use target-owned names",
                )
            )
        if path.is_symlink():
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_symlink_forbidden",
                    normalized,
                    "consumer distributions contain regular files only",
                )
            )
            continue
        actual[normalized] = _file_hash(path)
        text = _read_text(path)
        if text is not None:
            for code, pattern in FORBIDDEN_RUNTIME_PATTERNS:
                if pattern.search(text):
                    findings.append(
                        ConsumerDistributionFinding(
                            code,
                            normalized,
                            "consumer files must not depend on author-side SkillGuard",
                        )
                    )
    for missing in sorted(set(expected) - set(actual)):
        findings.append(
            ConsumerDistributionFinding(
                "consumer_file_missing",
                missing,
                "declared consumer file is absent",
            )
        )
    for unexpected in sorted(set(actual) - set(expected)):
        findings.append(
            ConsumerDistributionFinding(
                "consumer_file_unexpected",
                unexpected,
                "file is outside the frozen consumer release",
            )
        )
    for path in sorted(set(expected) & set(actual)):
        if expected[path] != actual[path]:
            findings.append(
                ConsumerDistributionFinding(
                    "consumer_file_hash_mismatch",
                    path,
                    "consumer file differs from the frozen release",
                )
            )
    return {
        "schema_version": CONSUMER_RELEASE_SCHEMA,
        "status": "blocked" if findings else "passed",
        "skill_id": str(manifest.get("skill_id", "")),
        "release_id": str(manifest.get("release_id", "")),
        "member_count": len(actual),
        "member_paths_hash": canonical_hash(sorted(actual)),
        "findings": [finding.to_dict() for finding in findings],
        "manifest": manifest,
    }
